// Generated by Selenium IDE
const { Builder, By, Key, until } = require("selenium-webdriver");
const assert = require("assert");

let chromeCapabilities = webdriver.Capabilities.chrome();
chromeCapabilities.set("chromeOptions", {
  args: [
    "--headless",
    "--no-sandbox",
    "--disable-dev-shm-usage",
    "--disable-gpu",
  ],
});

describe("Advanced Search", function () {
  this.timeout(30000);
  let driver;
  let vars;
  beforeEach(async function () {
    driver = await new Builder().forBrowser("chrome").build();
    vars = {};
  });
  afterEach(async function () {
    await driver.quit();
  });
  it("Advanced Search by Search Field", async function () {
    await driver.get("http://dev.cascprojects.org/");
    await driver.manage().window().setRect({ width: 896, height: 1097 });
    await driver.findElement(By.css(".btn-success")).click();
    await driver.findElement(By.id("queryTerms")).click();
    await driver.findElement(By.id("queryTerms")).sendKeys("tree");
    await driver.findElement(By.id("queryTerms")).sendKeys(Key.ENTER);
    await driver
      .findElement(By.xpath("(//input[@type='text'])[4]"))
      .sendKeys("North Central CASC");
    await driver
      .findElement(By.xpath("(//input[@type='text'])[4]"))
      .sendKeys(Key.ENTER);
    await driver.findElement(By.css(".btn-success")).click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
          ),
        )
        .getText()) ==
        "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
    );
  });
  it("Advanced Search by CASCs", async function () {
    await driver.get("http://dev.cascprojects.org/");
    await driver.manage().window().setRect({ width: 896, height: 1097 });
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div/form/div[4]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(By.xpath("//span[contains(text(), 'National CASC')]"))
      .click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "2010 Yearly Report for Predicting Climate Change Threats to Key Estuarine Habitats and Ecosystem Services in the Pacific Northwest",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "2010 Yearly Report for Predicting Climate Change Threats to Key Estuarine Habitats and Ecosystem Services in the Pacific Northwest",
          ),
        )
        .getText()) ==
        "2010 Yearly Report for Predicting Climate Change Threats to Key Estuarine Habitats and Ecosystem Services in the Pacific Northwest",
    );
  });
  it("Advanced Search by Subfilter", async function () {
    await driver.get("http://dev.cascprojects.org/");
    await driver.manage().window().setRect({ width: 896, height: 1097 });
    await driver.wait(
      until.elementLocated(By.css(".ng-select-single > .ng-select-container")),
      30000,
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[1]/form/div[2]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(
        By.xpath("//span[contains(text(), 'Drought, Fire and Extreme Weat')]"),
      )
      .click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
          ),
        )
        .getText()) ==
        "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[1]/form/div[3]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(By.xpath("//span[contains(text(), 'Extreme Weather')]"))
      .click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "21st Century High-Resolution Climate Projections for Guam and American Samoa",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "21st Century High-Resolution Climate Projections for Guam and American Samoa",
          ),
        )
        .getText()) ==
        "21st Century High-Resolution Climate Projections for Guam and American Samoa",
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[2]/div[1]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(By.xpath("//span[contains(text(), 'Project')]"))
      .click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "A Climate Risk Management Screening and Assessment Review for Madagascar’s Country Development Cooperation Strategy",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "A Climate Risk Management Screening and Assessment Review for Madagascar’s Country Development Cooperation Strategy",
          ),
        )
        .getText()) ==
        "A Climate Risk Management Screening and Assessment Review for Madagascar’s Country Development Cooperation Strategy",
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[2]/div[2]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(By.xpath("//span[contains(text(), '2014')]"))
      .click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "Changes to Watershed Vulnerability under Future Climates, Fire Regimes, and Population Pressures",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "Changes to Watershed Vulnerability under Future Climates, Fire Regimes, and Population Pressures",
          ),
        )
        .getText()) ==
        "Changes to Watershed Vulnerability under Future Climates, Fire Regimes, and Population Pressures",
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[2]/div[3]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(By.xpath("//span[contains(text(), 'In Progress')]"))
      .click();
    await driver.wait(
      until.elementLocated(
        By.linkText("Ecological Drought Across the Country"),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(By.linkText("Ecological Drought Across the Country"))
        .getText()) == "Ecological Drought Across the Country",
    );
  });
  it("Advanced Search by Topic and Subtopic", async function () {
    await driver.get("http://dev.cascprojects.org/");
    await driver.manage().window().setRect({ width: 896, height: 1097 });
    await driver.wait(
      until.elementLocated(By.css(".ng-select-single > .ng-select-container")),
      30000,
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[1]/form/div[2]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(
        By.xpath("//span[contains(text(), 'Drought, Fire and Extreme Weat')]"),
      )
      .click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
          ),
        )
        .getText()) ==
        "1200 Years of Upper Missouri River Streamflow Reconstructed from Tree Rings",
    );
    await driver
      .findElement(
        By.xpath(
          '//*[@id="mainDisplayWrapper"]/app-cscs/div/div[3]/div/app-search/div/div[1]/app-search-nav/div/div[1]/form/div[3]/ng-select/div',
        ),
      )
      .click();
    await driver
      .findElement(By.xpath("//span[contains(text(), 'Extreme Weather')]"))
      .click();
    await driver.findElement(By.css(".btn-success")).click();
    await driver.wait(
      until.elementLocated(
        By.linkText(
          "21st Century High-Resolution Climate Projections for Guam and American Samoa",
        ),
      ),
      30000,
    );
    assert(
      (await driver
        .findElement(
          By.linkText(
            "21st Century High-Resolution Climate Projections for Guam and American Samoa",
          ),
        )
        .getText()) ==
        "21st Century High-Resolution Climate Projections for Guam and American Samoa",
    );
  });
});
