// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Explore by Region', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Explore Projects by Alaska Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.wait(until.elementLocated(By.css("area:nth-child(1)")), 30000)
    await driver.findElement(By.css("area:nth-child(1)")).click()
    await driver.wait(until.elementLocated(By.linkText("Climate Vulnerability of Aquatic Species to Changing Stream Temperatures and Wildfire Across the Yukon and Kuskokwim River Basins, Alaska")), 30000)
    {
      const elements = await driver.findElements(By.linkText("Climate Vulnerability of Aquatic Species to Changing Stream Temperatures and Wildfire Across the Yukon and Kuskokwim River Basins, Alaska"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Climate Vulnerability of Aquatic Species to Changing Stream Temperatures and Wildfire Across the Yukon and Kuskokwim River Basins, Alaska")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Climate Vulnerability of Aquatic Species to Changing Stream Temperatures and Wildfire Across the Yukon and Kuskokwim River Basins, Alaska")
    {
      const elements = await driver.findElements(By.linkText("Alaska CASC"))
      assert(elements.length)
    }
  })
  it('Explore Projects by Midwest Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(7)")).click()
    await driver.wait(until.elementLocated(By.linkText("Relieving the Sting: Spatial Prioritization for Pollinator Conservation Under a Changing Climate")), 30000)
    {
      const elements = await driver.findElements(By.linkText("Relieving the Sting: Spatial Prioritization for Pollinator Conservation Under a Changing Climate"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Relieving the Sting: Spatial Prioritization for Pollinator Conservation Under a Changing Climate")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Relieving the Sting: Spatial Prioritization for Pollinator Conservation Under a Changing Climate")
  })
  it('Explore Projects by National CASC', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(10)")).click()
    await driver.wait(until.elementLocated(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities")), 30000)
    await driver.findElement(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Understanding how biodiversity affects ecosystem functioning in cities")
  })
  it('Explore Projects by North Central Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(5)")).click()
    await driver.wait(until.elementLocated(By.linkText("Snowpack Futures: Developing Management Tools to Address Snow as a Water Resource and Hazard")), 30000)
    await driver.findElement(By.linkText("Snowpack Futures: Developing Management Tools to Address Snow as a Water Resource and Hazard")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Snowpack Futures: Developing Management Tools to Address Snow as a Water Resource and Hazard")
  })
  it('Explore Projects by Southwest Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(4)")).click()
    await driver.wait(until.elementLocated(By.linkText("From Refugia to Resilience: Wildfires, Changing Climate, and Landscape Transformation in the Southwestern U.S.")), 30000)
    await driver.findElement(By.linkText("From Refugia to Resilience: Wildfires, Changing Climate, and Landscape Transformation in the Southwestern U.S.")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "From Refugia to Resilience: Wildfires, Changing Climate, and Landscape Transformation in the Southwestern U.S.")
  })
  it('Explore Projects by Southeast Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(8)")).click()
    await driver.wait(until.elementLocated(By.linkText("Improving Land Change Models for Climate Adaptation, Urban Development, and Conservation Action Across the US Caribbean")), 30000)
    await driver.findElement(By.linkText("Improving Land Change Models for Climate Adaptation, Urban Development, and Conservation Action Across the US Caribbean")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Improving Land Change Models for Climate Adaptation, Urban Development, and Conservation Action Across the US Caribbean")
  })
  it('Explore Projects by South Central Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(6)")).click()
    await driver.wait(until.elementLocated(By.linkText("Coastal Wetland Dynamics and Impacts on Hurricane Flood Risk along the Texas Gulf Coast in a Changing Climate")), 30000)
    await driver.findElement(By.linkText("Coastal Wetland Dynamics and Impacts on Hurricane Flood Risk along the Texas Gulf Coast in a Changing Climate")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Coastal Wetland Dynamics and Impacts on Hurricane Flood Risk along the Texas Gulf Coast in a Changing Climate")
  })
  it('Explore Projects by Pacific Islands Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(2)")).click()
    await driver.wait(until.elementLocated(By.linkText("Improving the Availability and Accessibility of Climate Information for Users in Hawai‘i, American Sāmoa, and Guam")), 30000)
    await driver.findElement(By.linkText("Improving the Availability and Accessibility of Climate Information for Users in Hawai‘i, American Sāmoa, and Guam")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Improving the Availability and Accessibility of Climate Information for Users in Hawai‘i, American Sāmoa, and Guam")
  })
  it('Explore Projects by Northwest Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(3)")).click()
    await driver.wait(until.elementLocated(By.linkText("Post-fire Vegetation Transitions in Burned and Reburned Forests in the Western Cascades")), 30000)
    {
      const elements = await driver.findElements(By.linkText("Post-fire Vegetation Transitions in Burned and Reburned Forests in the Western Cascades"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Post-fire Vegetation Transitions in Burned and Reburned Forests in the Western Cascades")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Post-fire Vegetation Transitions in Burned and Reburned Forests in the Western Cascades")
  })
  it('Explore Projects by Northeast Region', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.css("area:nth-child(9)")).click()
    await driver.wait(until.elementLocated(By.linkText("Impacts and Adaptation Strategies for Invasive Forest Insects and Diseases in the Northeast")), 30000)
    await driver.findElement(By.linkText("Impacts and Adaptation Strategies for Invasive Forest Insects and Diseases in the Northeast")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Impacts and Adaptation Strategies for Invasive Forest Insects and Diseases in the Northeast")
  })
})
