// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Explore by Topics', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Explore Projects by Drought, Fire and Extreme Topic', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.linkText("Drought, Fire and Extreme Weather")).click()
    await driver.wait(until.elementLocated(By.linkText("A Climate Risk Management Screening and Assessment Review for Madagascar’s Country Development Cooperation Strategy")), 30000)
    await driver.findElement(By.linkText("A Climate Risk Management Screening and Assessment Review for Madagascar’s Country Development Cooperation Strategy")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "A Climate Risk Management Screening and Assessment Review for Madagascar’s Country Development Cooperation Strategy")
  })
  it('Explore Projects by Indigenous Peoples Topic', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.linkText("Indigenous Peoples")).click()
    await driver.wait(until.elementLocated(By.linkText("Developing Adaptation Strategies for Recreational and Tribal Fisheries in the Upper Midwest")), 30000)
    await driver.findElement(By.linkText("Developing Adaptation Strategies for Recreational and Tribal Fisheries in the Upper Midwest")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Developing Adaptation Strategies for Recreational and Tribal Fisheries in the Upper Midwest")
  })
  it('Explore Projects by Science Tools for Manager Topic', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.linkText("Science Tools for Managers")).click()
    await driver.wait(until.elementLocated(By.linkText("A Guide to Modeling Low Flows and Intermittent Streams in the Pacific Northwest")), 30000)
    await driver.findElement(By.linkText("A Guide to Modeling Low Flows and Intermittent Streams in the Pacific Northwest")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "A Guide to Modeling Low Flows and Intermittent Streams in the Pacific Northwest")
  })
  it('Explore Projects by Landscapes Topic', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.linkText("Landscapes")).click()
    await driver.wait(until.elementLocated(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities")), 30000)
    {
      const elements = await driver.findElements(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities"))
      assert(elements.length)
    }
    await driver.findElement(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    {
      const elements = await driver.findElements(By.css(".col-md-8 > h1"))
      assert(elements.length)
    }
  })
  it('Explore Projects by Water, Coasts and Ice Topic', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.linkText("Water, Coasts and Ice")).click()
    await driver.wait(until.elementLocated(By.linkText("Republic of Marshall Islands Precipitation and Vegetation Monitoring")), 30000)
    await driver.findElement(By.linkText("Republic of Marshall Islands Precipitation and Vegetation Monitoring")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Republic of Marshall Islands Precipitation and Vegetation Monitoring")
  })
  it('Explore Projects by Wildlife and Plants Topic', async function() {
    await driver.get("http://dev.cascprojects.org/")
    await driver.manage().window().setRect({ width: 896, height: 1097 })
    await driver.findElement(By.linkText("Wildlife and Plants")).click()
    await driver.wait(until.elementLocated(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities")), 30000)
    await driver.findElement(By.linkText("Understanding how biodiversity affects ecosystem functioning in cities")).click()
    await driver.wait(until.elementLocated(By.css(".col-md-8 > h1")), 30000)
    assert(await driver.findElement(By.css(".col-md-8 > h1")).getText() == "Understanding how biodiversity affects ecosystem functioning in cities")
  })
})
