name: Run Selenium tests using Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-ide-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install CASC node modules
        run: npm install

      - name: Run Advanced Search test
        run: npm run test-search
