name: Run Selenium tests using Github Actions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-ide-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size 2g
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Selenium IDE Runner
        run: npm install selenium-side-runner

      - name: Report status of Selenium server
        run: |
          sleep 10 && curl -sSL http://selenium:4444/wd/hub/status

      - name: Run Selenium IDE tests
        run: selenium-side-runner ./selenium-tests/CASC\ Project\ Explorer.side --server http://selenium:4444/wd/hub
